# Generated by Django 3.0.8 on 2020-07-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20200708_1201")]

    operations = [
        migrations.RemoveField(model_name="customuser", name="main_user"),
        migrations.AlterField(
            model_name="customuser",
            name="public_email",
            field=models.BooleanField(default=False, verbose_name="Main User"),
        ),
    ]
