# Generated by Django 3.0.8 on 2020-07-03 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=150, verbose_name="Tag")),
                (
                    "img_link",
                    models.CharField(max_length=255, verbose_name="Image url"),
                ),
                (
                    "description",
                    models.CharField(max_length=280, verbose_name="Description"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.CharField(max_length=280, verbose_name="Description"),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Use Markdown syntax", verbose_name="Content"
                    ),
                ),
                (
                    "img_link",
                    models.CharField(max_length=255, verbose_name="Image url"),
                ),
                (
                    "created_on",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated_on",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                ("views", models.IntegerField(default=0, verbose_name="Views")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="articles.Tag", verbose_name="Tags"),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "ordering": ["-created_on"],
            },
        ),
    ]
