# Generated by Django 3.0.8 on 2020-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("articles", "0003_auto_20200717_1302")]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Product")),
                ("abbr", models.CharField(max_length=4, verbose_name="Product")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "description",
                    models.CharField(max_length=280, verbose_name="Description"),
                ),
                ("price", models.PositiveSmallIntegerField(verbose_name="Price")),
                (
                    "tags",
                    models.ManyToManyField(to="articles.Tag", verbose_name="Tags"),
                ),
            ],
            options={"verbose_name": "Product", "verbose_name_plural": "Product"},
        )
    ]
